# Basics of PyTorch

This code creates various tensors and performs basic operations on them, such as reshaping, indexing, and slicing. It also shows how to move a tensor to the GPU if available.

In [ ]:
import torch

# create a tensor from a list
x = torch.tensor([1, 2, 3])

# create a tensor from a numpy array
import numpy as np
y = np.array([[1, 2, 3], [4, 5, 6]])
z = torch.from_numpy(y)

# create a tensor of zeros with shape (2, 3)
a = torch.zeros(2, 3)

# create a tensor of ones with shape (2, 3)
b = torch.ones(2, 3)

# create a random tensor with shape (2, 3)
c = torch.randn(2, 3)

# reshape a tensor
d = torch.arange(6).reshape(2, 3)

# get the size of a tensor
size = d.size()

# indexing and slicing a tensor
e = d[1, 2]
f = d[:, 1:3]


In [ ]:
# move a tensor to the GPU if available
if torch.cuda.is_available():
  device = torch.device("cuda")
  j = c.to(device)


In [ ]:
# create tensors
x = torch.tensor([1, 2, 3])
y = np.array([4, 5, 6])

# convert NumPy array to PyTorch tensor
y_tensor = torch.from_numpy(y)

# element-wise addition
g = x + y_tensor
h = torch.add(x, y_tensor)

print(g)  # output: tensor([5, 7, 9])
print(h)  # output: tensor([5, 7, 9])

tensor([5, 7, 9])
tensor([5, 7, 9])


## Tensor Broadcasting

Tensor broadcasting is a technique in which tensors with different shapes can be combined in arithmetic operations. PyTorch automatically broadcasts tensors to have the same shape by duplicating the tensor with the smaller shape along the appropriate dimensions.

In [ ]:
import torch

# create a tensor with shape (3, 1)
x = torch.tensor([1, 2, 3]).view(3, 1)

x

tensor([[1],
        [2],
        [3]])

In [ ]:
# create a tensor with shape (1, 4)
y = torch.tensor([4, 5, 6, 7]).view(1, 4)

y

tensor([[4, 5, 6, 7]])

In [ ]:
# add the tensors together
z = x + y

print(z)

tensor([[ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 7,  8,  9, 10]])


In this example, x has shape (3, 1) and y has shape (1, 4). When we add them together, PyTorch automatically broadcasts x to have shape (3, 4) by duplicating the elements along the second dimension. The resulting tensor z has shape (3, 4) and contains the element-wise sum of x and y.

## Tensor Concatenation

Tensor concatenation is a technique in which two or more tensors are combined along a given dimension. In PyTorch, you can use the torch.cat() function to concatenate tensors along a specified dimension.

In [ ]:
import torch

# create two tensors with shape (2, 3)
x = torch.ones(2, 3)
y = torch.zeros(2, 3)

# concatenate the tensors along the first dimension
z = torch.cat([x, y], dim=0)

print(z)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In this example, x and y both have shape (2, 3). We concatenate them along the first dimension (the rows) using the torch.cat() function. The resulting tensor z has shape (4, 3) and contains the rows of x followed by the rows of y.

## Tensor Reduction Operations

Tensor reduction operations are used to reduce the dimensionality of a tensor by performing a mathematical operation across one or more dimensions. In PyTorch, you can use various reduction operations such as sum(), mean(), max(), min(), argmax(), and argmin().

In [ ]:
import torch

# Create a tensor
x = torch.tensor([[1, 2], [3, 4]])

# Sum of all elements in the tensor
sum_x = torch.sum(x)
print("Sum of all elements:", sum_x.item())

# Sum along rows
sum_row_x = torch.sum(x, dim=1)
print("Sum along rows:", sum_row_x)

# Sum along columns
sum_col_x = torch.sum(x, dim=0)
print("Sum along columns:", sum_col_x)

# Maximum element in the tensor
max_x = torch.max(x)
print("Maximum element:", max_x.item())

# Maximum element along rows
max_row_x = torch.max(x, dim=1)
print("Maximum element along rows:", max_row_x.values)

# Maximum element along columns
max_col_x = torch.max(x, dim=0)
print("Maximum element along columns:", max_col_x.values)

# Minimum element in the tensor
min_x = torch.min(x)
print("Minimum element:", min_x.item())

# Minimum element along rows
min_row_x = torch.min(x, dim=1)
print("Minimum element along rows:", min_row_x.values)

# Minimum element along columns
min_col_x = torch.min(x, dim=0)
print("Minimum element along columns:", min_col_x.values)


Sum of all elements: 10
Sum along rows: tensor([3, 7])
Sum along columns: tensor([4, 6])
Maximum element: 4
Maximum element along rows: tensor([2, 4])
Maximum element along columns: tensor([3, 4])
Minimum element: 1
Minimum element along rows: tensor([1, 3])
Minimum element along columns: tensor([1, 2])


## A Simple Implementation of NN with PyTorch

In this example, we define a simple neural network with 3 fully connected layers (with 784, 128, and 64 nodes, respectively) and use the ReLU activation function. We then define the loss function (cross-entropy loss) and optimizer (stochastic gradient descent), and train the network on a dataset using a for loop.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Define the neural network architecture
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Create an instance of the neural network
net = Net()

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

# Load the training data
trainset = datasets.MNIST('data', train=True, download=True, transform=transforms.ToTensor())
trainloader = DataLoader(trainset, batch_size=64, shuffle=True)

# Train the neural network
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        if i % 1000 == 999:    # Print every 1000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 1000))
            running_loss = 0.0

print('Finished Training')


  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw

Finished Training
